dags:
  persistence:
    enabled: false
  gitSync:
    enabled: true
    repo: "https://github.com/Abdullah03366/test_airflow.git"
    branch: main
    rev: HEAD
    subPath: "."
    wait: 30
    depth: 1
