dags:
  persistence:
    enabled: false
  gitSync:
    enabled: true
    repo: "https://github.com/Abdullah03366/test_airflow.git"
    branch: main
    rev: HEAD
    subPath: dags
    wait: 15
    depth: 1

airflow:
  extraPipPackages:
    - "apache-airflow-providers-ssh"
