apiVersion: v1
kind: Service
metadata:
  name: ssh-grep
spec:
  selector:
    app: ssh-grep
  ports:
    - port: 22        # dit is de port in-cluster
      targetPort: 22  # containerpoort
  type: ClusterIP
